const termList = [
    // Basic Terms
    { jp: "ファイアウォール", en: "FIREWALL" },
    { jp: "マルウェア", en: "MALWARE" },
    { jp: "ウイルス", en: "VIRUS" },
    { jp: "トロイの木馬", en: "TROJAN" },
    { jp: "ワーム", en: "WORM" },
    { jp: "スパイウェア", en: "SPYWARE" },
    { jp: "ランサムウェア", en: "RANSOMWARE" },
    { jp: "フィッシング", en: "PHISHING" },
    { jp: "脆弱性", en: "VULNERABILITY" },
    { jp: "エクスプロイト", en: "EXPLOIT" },
    { jp: "バグ", en: "BUG" },
    { jp: "パッチ", en: "PATCH" },
    { jp: "ハッキング", en: "HACKING" },
    { jp: "サイバー", en: "CYBER" },
    { jp: "セキュリティ", en: "SECURITY" },
    { jp: "アラート", en: "ALERT" },
    { jp: "アクセス", en: "ACCESS" },
    { jp: "ログイン", en: "LOGIN" },
    { jp: "ログアウト", en: "LOGOUT" },
    { jp: "管理者", en: "ADMIN" },

    // Network & Infrastructure
    { jp: "プロトコル", en: "PROTOCOL" },
    { jp: "パケット", en: "PACKET" },
    { jp: "サーバー", en: "SERVER" },
    { jp: "クライアント", en: "CLIENT" },
    { jp: "クラウド", en: "CLOUD" },
    { jp: "VPN", en: "VPN" },
    { jp: "プロキシ", en: "PROXY" },
    { jp: "ルーター", en: "ROUTER" },
    { jp: "スイッチ", en: "SWITCH" },
    { jp: "ゲートウェイ", en: "GATEWAY" },
    { jp: "ポート", en: "PORT" },
    { jp: "IPアドレス", en: "IP ADDRESS" },
    { jp: "MACアドレス", en: "MAC ADDRESS" },
    { jp: "ドメイン", en: "DOMAIN" },
    { jp: "DNS", en: "DNS" },
    { jp: "DHCP", en: "DHCP" },
    { jp: "イントラネット", en: "INTRANET" },
    { jp: "インターネット", en: "INTERNET" },
    { jp: "DMZ", en: "DMZ" },
    { jp: "帯域幅", en: "BANDWIDTH" },
    { jp: "レイテンシ", en: "LATENCY" },

    // Auth & Crypto
    { jp: "認証", en: "AUTHENTICATION" },
    { jp: "認可", en: "AUTHORIZATION" },
    { jp: "暗号化", en: "ENCRYPTION" },
    { jp: "復号", en: "DECRYPTION" },
    { jp: "ハッシュ", en: "HASH" },
    { jp: "ブロックチェーン", en: "BLOCKCHAIN" },
    { jp: "多要素認証", en: "MFA" },
    { jp: "生体認証", en: "BIOMETRIC" },
    { jp: "公開鍵", en: "PUBLIC KEY" },
    { jp: "秘密鍵", en: "PRIVATE KEY" },
    { jp: "電子署名", en: "SIGNATURE" },
    { jp: "証明書", en: "CERTIFICATE" },
    { jp: "トークン", en: "TOKEN" },
    { jp: "パスワード", en: "PASSWORD" },
    { jp: "ワンタイム", en: "ONE TIME" },
    { jp: "SSL/TLS", en: "SSL TLS" },
    { jp: "RSA", en: "RSA" },

    // Attack Vectors & Methods
    { jp: "バックドア", en: "BACKDOOR" },
    { jp: "ボットネット", en: "BOTNET" },
    { jp: "ゼロデイ", en: "ZERO DAY" },
    { jp: "ソーシャルエンジニアリング", en: "SOCIAL ENGINEERING" },
    { jp: "権限昇格", en: "PRIVILEGE ESCALATION" },
    { jp: "盗聴", en: "EAVESDROPPING" },
    { jp: "改ざん", en: "TAMPERING" },
    { jp: "なりすまし", en: "SPOOFING" },
    { jp: "否認", en: "REPUDIATION" },
    { jp: "ブルートフォース", en: "BRUTE FORCE" },
    { jp: "辞書攻撃", en: "DICTIONARY ATTACK" },
    { jp: "SQLインジェクション", en: "SQL INJECTION" },
    { jp: "クロスサイトスクリプト", en: "XSS" },
    { jp: "中間者攻撃", en: "MAN IN THE MIDDLE" },
    { jp: "サービス拒否", en: "DOS" },
    { jp: "DDoS攻撃", en: "DDOS" },
    { jp: "キーロガー", en: "KEYLOGGER" },
    { jp: "ルートキット", en: "ROOTKIT" },
    { jp: "スパム", en: "SPAM" },
    { jp: "標的型攻撃", en: "APT" },
    { jp: "踏み台", en: "JUMPHOST" },
    { jp: "水飲み場攻撃", en: "WATERINGHOLE" },
    { jp: "クリックジャッキング", en: "CLICKJACKING" },

    // Security Management & Concepts
    { jp: "リスク", en: "RISK" },
    { jp: "資産", en: "ASSET" },
    { jp: "脅威", en: "THREAT" },
    { jp: "監査", en: "AUDIT" },
    { jp: "コンプライアンス", en: "COMPLIANCE" },
    { jp: "ポリシー", en: "POLICY" },
    { jp: "インテグリティ", en: "INTEGRITY" },
    { jp: "可用性", en: "AVAILABILITY" },
    { jp: "機密性", en: "CONFIDENTIALITY" },
    { jp: "情報漏洩", en: "LEAKAGE" },
    { jp: "バックアップ", en: "BACKUP" },
    { jp: "リカバリ", en: "RECOVERY" },
    { jp: "検知", en: "DETECTION" },
    { jp: "防御", en: "DEFENSE" },
    { jp: "監視", en: "MONITORING" },
    { jp: "ログ", en: "LOG" },
    { jp: "分析", en: "ANALYSIS" },
    { jp: "フォレンジック", en: "FORENSICS" },
    { jp: "ペネトレーションテスト", en: "PENTEST" },
    { jp: "バグバウンティ", en: "BUGBOUNTY" },
    { jp: "インシデント", en: "INCIDENT" },
    { jp: "CSIRT", en: "CSIRT" },
    { jp: "SOC", en: "SOC" },
    { jp: "ゼロトラスト", en: "ZEROTRUST" },

    // Hardware & OS & General IT
    { jp: "バイオス", en: "BIOS" },
    { jp: "カーネル", en: "KERNEL" },
    { jp: "メモリ", en: "MEMORY" },
    { jp: "CPU", en: "CPU" },
    { jp: "GPU", en: "GPU" },
    { jp: "ストレージ", en: "STORAGE" },
    { jp: "USB", en: "USB" },
    { jp: "ファームウェア", en: "FIRMWARE" },
    { jp: "ドライバ", en: "DRIVER" },
    { jp: "仮想化", en: "VIRTUALIZATION" },
    { jp: "コンテナ", en: "CONTAINER" },
    { jp: "IoT", en: "IOT" },
    { jp: "OS", en: "OS" },
    { jp: "Windows", en: "WINDOWS" },
    { jp: "Linux", en: "LINUX" },
    { jp: "Mac", en: "MAC" },
    { jp: "Android", en: "ANDROID" },
    { jp: "iOS", en: "IOS" },
    { jp: "データベース", en: "DATABASE" },
    { jp: "アルゴリズム", en: "ALGORITHM" },

    // Advanced & Slang
    { jp: "ホワイトハット", en: "WHITEHAT" },
    { jp: "ブラックハット", en: "BLACKHAT" },
    { jp: "グレーハット", en: "GRAYHAT" },
    { jp: "スクリプトキディ", en: "SCRIPTKIDDIE" },
    { jp: "ハクティビスト", en: "HACKTIVIST" },
    { jp: "ダークウェブ", en: "DARKWEB" },
    { jp: "ディープウェブ", en: "DEEPWEB" },
    { jp: "Tor", en: "TOR" },
    { jp: "ビットコイン", en: "BITCOIN" },
    { jp: "エビデンス", en: "EVIDENCE" },
    { jp: "隔離", en: "ISOLATION" },
    { jp: "サニタイズ", en: "SANITIZATION" },
    { jp: "フィルタリング", en: "FILTERING" },
    { jp: "ホワイトリスト", en: "WHITELIST" },
    { jp: "ブラックリスト", en: "BLACKLIST" },
    { jp: "サンドボックス", en: "SANDBOX" },
    { jp: "ハニーポット", en: "HONEYPOT" },

    // Legal, Compliance & Standards
    { jp: "個人情報", en: "PERSONALDATA" },
    { jp: "プライバシー", en: "PRIVACY" },
    { jp: "著作権", en: "COPYRIGHT" },

    // DevSecOps & Modern IT
    { jp: "パイプライン", en: "PIPELINE" },
    { jp: "デプロイ", en: "DEPLOY" },
    { jp: "リポジトリ", en: "REPOSITORY" },
    { jp: "マイクロサービス", en: "MICROSERVICES" },
    { jp: "サーバーレス", en: "SERVERLESS" },
    { jp: "シャドーIT", en: "SHADOWIT" },

    // Cryptography & Keys (Detailed)
    { jp: "共通鍵", en: "COMMONKEY" }, // 対称鍵
    { jp: "鍵交換", en: "KEYEXCHANGE" },
    { jp: "乱数", en: "RANDOMNUMBER" },

    // Defense & Countermeasures
    { jp: "堅牢化", en: "HARDENING" },
    { jp: "難読化", en: "OBFUSCATION" },
    { jp: "検疫", en: "QUARANTINE" },
    { jp: "シグネチャ", en: "SIGNATURE" }, // ウイルス定義など
    { jp: "エアギャップ", en: "AIRGAP" }, // 物理的遮断
    { jp: "最小権限", en: "LEASTPRIVILEGE" },
    { jp: "多層防御", en: "DEFENSEINDEPTH" },

    // Web Application Security
    { jp: "クッキー", en: "COOKIE" },
    { jp: "セッション", en: "SESSION" },

];
