const termList = [
    { jp: "能力", en: "Ability" },
    { jp: "～を悪用する 悪用、不正行為", en: "Abuse" },
    { jp: "アクセス", en: "Access" },
    { jp: "～によれば", en: "According" },
    { jp: "アカウント、口座", en: "Account" },
    { jp: "〜を達成する、獲得する", en: "Achieve" },
    { jp: "攻撃者グループ、アクター", en: "Actor" },
    { jp: "付加", en: "Addition" },
    { jp: "(問題やバグなど)に対処する 住所、アドレス", en: "Address" },
    { jp: "管理者", en: "Admin" },
    { jp: "管理者", en: "Administrator" },
    { jp: "〜を認める、入れる", en: "Admit" },
    { jp: "進歩する 進歩、前進", en: "Advance" },
    { jp: "(take advantage of～で)～を利用する", en: "Advantage" },
    { jp: "～を忠告する、勧める", en: "Advise" },
    { jp: "〜に影響する", en: "Affect" },
    { jp: "加盟メンバー ～に加盟する", en: "Affiliate" },
    { jp: "機関", en: "Agency" },
    { jp: "〜を狙う、目指す 狙い、目的", en: "Aim" },
    { jp: "エアギャップ", en: "Airgap" },
    { jp: "アラート", en: "Alert" },
    { jp: "アルゴリズム", en: "Algorithm" },
    { jp: "〜と主張する", en: "Allege" },
    { jp: "～を可能とする、許可する", en: "Allow" },
    { jp: "量、総計 (to～で)～に達する", en: "Amount" },
    { jp: "分析", en: "Analysis" },
    { jp: "～を分析する", en: "Analyze" },
    { jp: "Android", en: "Android" },
    { jp: "～を付け加える", en: "Append" },
    { jp: "取り組み方、接近 取り組み方、接近", en: "Approach" },
    { jp: "おおよそ", en: "Approximately" },
    { jp: "標的型攻撃", en: "Apt" },
    { jp: "任意の", en: "Arbitrary" },
    { jp: "～と主張する", en: "Argue" },
    { jp: "記事", en: "Article" },
    { jp: "資産", en: "Asset" },
    { jp: "～と関連付ける 仲間", en: "Associate" },
    { jp: "～を添付する、取り付ける", en: "Attach" },
    { jp: "～を試みる 試み", en: "Attempt" },
    { jp: "監査", en: "Audit" },
    { jp: "～を認証する", en: "Authenticate" },
    { jp: "認証", en: "Authentication" },
    { jp: "当局、権威", en: "Authority" },
    { jp: "認可", en: "Authorization" },
    { jp: "～を認可する、権限を与える", en: "Authorize" },
    { jp: "～を自動化する", en: "Automate" },
    { jp: "可用性", en: "Availability" },
    { jp: "利用可能である", en: "Available" },
    { jp: "～を避ける", en: "Avoid" },
    { jp: "～を知っている", en: "Aware" },
    { jp: "バックドア", en: "Backdoor" },
    { jp: "バックアップ", en: "Backup" },
    { jp: "帯域幅", en: "Bandwidth" },
    { jp: "〜を基盤とする、～に基づく 基盤、基礎、基数", en: "Base" },
    { jp: "挙動、振る舞い", en: "Behavior" },
    { jp: "～に属する", en: "Belong" },
    { jp: "生体認証", en: "Biometric" },
    { jp: "バイオス", en: "Bios" },
    { jp: "ビットコイン", en: "Bitcoin" },
    { jp: "ブラックハット", en: "Blackhat" },
    { jp: "ブラックリスト", en: "Blacklist" },
    { jp: "〜を遮断する ブロック、遮断", en: "Block" },
    { jp: "ブロックチェーン", en: "Blockchain" },
    { jp: "ボットネット", en: "Botnet" },
    { jp: "報奨金", en: "Bounty" },
    { jp: "(データの)流出、侵害 ～を侵害しデータを持ち出す", en: "Breach" },
    { jp: "ブルートフォース", en: "Brute force" },
    { jp: "バグ", en: "Bug" },
    { jp: "バグバウンティ", en: "Bugbounty" },
    { jp: "～を迂回する 迂回、バイパス", en: "Bypass" },
    { jp: "一連の作戦、キャンペーン", en: "Campaign" },
    { jp: "能力", en: "Capability" },
    { jp: "ある特定の、確かな", en: "Certain" },
    { jp: "証明書", en: "Certificate" },
    { jp: "経路、チャンネル", en: "Channel" },
    { jp: "～を告発する、請求する 請求、告発", en: "Charge" },
    { jp: "〜と主張する 主張、要求", en: "Claim" },
    { jp: "クリックジャッキング", en: "Clickjacking" },
    { jp: "クライアント", en: "Client" },
    { jp: "クラウド", en: "Cloud" },
    { jp: "コード、符号", en: "Code" },
    { jp: "(罪など)を犯す、～を約束する", en: "Commit" },
    { jp: "共通鍵", en: "Commonkey" },
    { jp: "苦情、告訴", en: "Complaint" },
    { jp: "～を完了する 全部の、完全な", en: "Complete" },
    { jp: "コンプライアンス", en: "Compliance" },
    { jp: "(システムなど)を侵害する", en: "Compromise" },
    { jp: "～に関係する 関係、関心事", en: "Concern" },
    { jp: "〜と結論づける", en: "Conclude" },
    { jp: "～を行う 行為", en: "Conduct" },
    { jp: "機密の", en: "Confidential" },
    { jp: "機密性", en: "Confidentiality" },
    { jp: "～を設定する", en: "Configure" },
    { jp: "〜を確認する", en: "Confirm" },
    { jp: "接続、コネクション", en: "Connection" },
    { jp: "～をよく考える、検討する、考慮する", en: "Consider" },
    { jp: "消費者", en: "Consumer" },
    { jp: "〜と接触する、連絡する 接触", en: "Contact" },
    { jp: "〜を含む", en: "Contain" },
    { jp: "コンテナ", en: "Container" },
    { jp: "内容、コンテンツ", en: "Content" },
    { jp: "クッキー", en: "Cookie" },
    { jp: "〜を調整する、まとめ上げる", en: "Coordinate" },
    { jp: "著作権", en: "Copyright" },
    { jp: "法人の、企業の", en: "Corporate" },
    { jp: "費用 (費用)がかかる", en: "Cost" },
    { jp: "裁判所", en: "Court" },
    { jp: "CPU", en: "Cpu" },
    { jp: "〜を破壊する、クラッシュする (装置・プログラムの)クラッシュ", en: "Crash" },
    { jp: "～を作り出す", en: "Create" },
    { jp: "認証情報", en: "Credential" },
    { jp: "犯罪", en: "Crime" },
    { jp: "重大な、致命的な", en: "Critical" },
    { jp: "暗号通貨", en: "Cryptocurrency" },
    { jp: "CSIRT", en: "Csirt" },
    { jp: "累積の", en: "Cumulative" },
    { jp: "現在の、最新の", en: "Current" },
    { jp: "顧客、取引先", en: "Customer" },
    { jp: "サイバー", en: "Cyber" },
    { jp: "ダークウェブ", en: "Darkweb" },
    { jp: "データベース", en: "Database" },
    { jp: "DDoS攻撃", en: "Ddos" },
    { jp: "～を復号する", en: "Decrypt" },
    { jp: "復号", en: "Decryption" },
    { jp: "ディープウェブ", en: "Deepweb" },
    { jp: "〜を防御する", en: "Defend" },
    { jp: "防御", en: "Defense" },
    { jp: "多層防御", en: "Defenseindepth" },
    { jp: "〜を削除する", en: "Delete" },
    { jp: "～を配送する", en: "Deliver" },
    { jp: "～を要求する 要求", en: "Demand" },
    { jp: "〜を示す、証明する", en: "Demonstrate" },
    { jp: "省、局", en: "Department" },
    { jp: "デプロイ", en: "Deploy" },
    { jp: "～と説明する、記述する", en: "Describe" },
    { jp: "細部、詳細 〜を詳細に述べる", en: "Detail" },
    { jp: "〜を検知する", en: "Detect" },
    { jp: "検知", en: "Detection" },
    { jp: "～を決心する、判断する", en: "Determine" },
    { jp: "DHCP", en: "Dhcp" },
    { jp: "辞書攻撃", en: "Dictionary attack" },
    { jp: "～を指示する、～へ案内する 直接の", en: "Direct" },
    { jp: "〜を無効化する", en: "Disable" },
    { jp: "〜を公表する、暴露する", en: "Disclose" },
    { jp: "～を表示する、展示する 表示、画面", en: "Display" },
    { jp: "～を中断させる、混乱させる", en: "Disrupt" },
    { jp: "～を配布する", en: "Distribute" },
    { jp: "DMZ", en: "Dmz" },
    { jp: "DNS", en: "Dns" },
    { jp: "ドメイン", en: "Domain" },
    { jp: "サービス拒否", en: "Dos" },
    { jp: "ドライバ", en: "Driver" },
    { jp: "(dueto〜の形で)〜を原因として", en: "Due" },
    { jp: "盗聴", en: "Eavesdropping" },
    { jp: "効果、影響", en: "Effect" },
    { jp: "選挙", en: "Election" },
    { jp: "(権限の)昇格", en: "Elevation" },
    { jp: "～を組み込む、埋め込む", en: "Embed" },
    { jp: "台頭する、現れる、明らかになる", en: "Emerge" },
    { jp: "緊急事態", en: "Emergency" },
    { jp: "～を雇う、使用する", en: "Employ" },
    { jp: "(設定などを) 有効化する、可能にする", en: "Enable" },
    { jp: "～を暗号化する", en: "Encrypt" },
    { jp: "暗号化", en: "Encryption" },
    { jp: "～を強要する、実施する", en: "Enforce" },
    { jp: "〜に携わる、〜を雇う", en: "Engage" },
    { jp: "〜を確実にする、保証する", en: "Ensure" },
    { jp: "企業", en: "Enterprise" },
    { jp: "全体の、完全な", en: "Entire" },
    { jp: "(人や組織などの)主体", en: "Entity" },
    { jp: "入り口、項目", en: "Entry" },
    { jp: "～を確立する", en: "Establish" },
    { jp: "エビデンス", en: "Evidence" },
    { jp: "～を実行する", en: "Execute" },
    { jp: "行政長官、経営者", en: "Executive" },
    { jp: "(データなど)を密かに流出させる", en: "Exfiltrate" },
    { jp: "存在する、すでにある", en: "Exist" },
    { jp: "広がる、〜を広げる", en: "Expand" },
    { jp: "〜を予期する、〜と推定する", en: "Expect" },
    { jp: "エクスプロイト", en: "Exploit" },
    { jp: "〜を暴露する", en: "Expose" },
    { jp: "～を拡張する、広げる", en: "Extend" },
    { jp: "外部の", en: "External" },
    { jp: "～を脅迫する、ゆすり取る", en: "Extort" },
    { jp: "失敗する", en: "Fail" },
    { jp: "偽の", en: "Fake" },
    { jp: "偽の、間違った", en: "False" },
    { jp: "特徴、目玉 ～を売りとする、特集する", en: "Feature" },
    { jp: "連邦の", en: "Federal" },
    { jp: "フィルタリング", en: "Filtering" },
    { jp: "金銭的な、金融の", en: "Financial" },
    { jp: "ファイアウォール", en: "Firewall" },
    { jp: "会社", en: "Firm" },
    { jp: "ファームウェア", en: "Firmware" },
    { jp: "(脆弱性やバグ)を修正する", en: "Fix" },
    { jp: "欠陥", en: "Flaw" },
    { jp: "～に集中する、焦点を当てる 焦点、中心", en: "Focus" },
    { jp: "～を強いる 強制、暴力", en: "Force" },
    { jp: "フォレンジック", en: "Forensics" },
    { jp: "形態、種類、フォーム", en: "Form" },
    { jp: "前の、先の", en: "Former" },
    { jp: "詐欺", en: "Fraud" },
    { jp: "詐欺師", en: "Fraudster" },
    { jp: "機能、関数 機能する", en: "Function" },
    { jp: "資金、基金 ～に資金提供する", en: "Fund" },
    { jp: "さらに進んだ さらに", en: "Further" },
    { jp: "～を獲得する 収益", en: "Gain" },
    { jp: "ゲートウェイ", en: "Gateway" },
    { jp: "～を生成する、生じさせる", en: "Generate" },
    { jp: "政府", en: "Government" },
    { jp: "GPU", en: "Gpu" },
    { jp: "グレーハット", en: "Grayhat" },
    { jp: "ハッキング", en: "Hacking" },
    { jp: "ハクティビスト", en: "Hacktivist" },
    { jp: "～を扱う、処理する", en: "Handle" },
    { jp: "堅牢化", en: "Hardening" },
    { jp: "ハッシュ", en: "Hash" },
    { jp: "～を隠す", en: "Hide" },
    { jp: "～を強調する 目玉、見どころ", en: "Highlight" },
    { jp: "ハニーポット", en: "Honeypot" },
    { jp: "〜を特定する", en: "Identify" },
    { jp: "識別情報", en: "Identity" },
    { jp: "画像、イメージ", en: "Image" },
    { jp: "即時の、即座の", en: "Immediate" },
    { jp: "～になりすます", en: "Impersonate" },
    { jp: "～を実装する、実行する", en: "Implement" },
    { jp: "インシデント", en: "Incident" },
    { jp: "～を含む", en: "Include" },
    { jp: "ますます", en: "Increasingly" },
    { jp: "～を示す、指摘する", en: "Indicate" },
    { jp: "個人 個人の、個々の", en: "Individual" },
    { jp: "産業、業界", en: "Industry" },
    { jp: "～に感染させる", en: "Infect" },
    { jp: "～に知らせる", en: "Inform" },
    { jp: "最初の", en: "Initial" },
    { jp: "〜を注入する、仕掛ける", en: "Inject" },
    { jp: "内部の人、会員", en: "Insider" },
    { jp: "例、インスタンス", en: "Instance" },
    { jp: "機関、団体", en: "Institution" },
    { jp: "説明、指示、命令", en: "Instruction" },
    { jp: "保険", en: "Insurance" },
    { jp: "インテグリティ", en: "Integrity" },
    { jp: "知能、インテリジェンス", en: "Intelligence" },
    { jp: "興味、関心事 興味を起こさせる", en: "Interest" },
    { jp: "内部の", en: "Internal" },
    { jp: "インターネット", en: "Internet" },
    { jp: "IoT", en: "Internet of things" },
    { jp: "イントラネット", en: "Intranet" },
    { jp: "～を投資する", en: "Invest" },
    { jp: "～を調査する", en: "Investigate" },
    { jp: "〜を巻き込む、関係させる", en: "Involve" },
    { jp: "iOS", en: "Ios" },
    { jp: "IPアドレス", en: "Ip address" },
    { jp: "隔離", en: "Isolation" },
    { jp: "問題(点) 〜を発行する", en: "Issue" },
    { jp: "踏み台", en: "Jumphost" },
    { jp: "カーネル", en: "Kernel" },
    { jp: "鍵交換", en: "Keyexchange" },
    { jp: "キーロガー", en: "Keylogger" },
    { jp: "既知の", en: "Known" },
    { jp: "レイテンシ", en: "Latency" },
    { jp: "～を立ち上げる、～を開始する 開始", en: "Launch" },
    { jp: "法", en: "Law" },
    { jp: "流出する、〜を流出させる (情報の)流出、リーク", en: "Leak" },
    { jp: "情報漏洩", en: "Leakage" },
    { jp: "最小権限", en: "Leastprivilege" },
    { jp: "法的な、法曹業界の、合法の", en: "Legal" },
    { jp: "正規の", en: "Legitimate" },
    { jp: "ありそうな おそらく", en: "Likely" },
    { jp: "～を限定する、制限する 限界、制限", en: "Limit" },
    { jp: "～と関連づける 関連、リンク", en: "Link" },
    { jp: "Linux", en: "Linux" },
    { jp: "〜に置く", en: "Locate" },
    { jp: "ログ", en: "Log" },
    { jp: "ログイン", en: "Login" },
    { jp: "ログアウト", en: "Logout" },
    { jp: "損害、喪失", en: "Loss" },
    { jp: "(相手を騙すための) おとり、ルアー ～を誘い込む", en: "Lure" },
    { jp: "Mac", en: "Mac" },
    { jp: "MACアドレス", en: "Mac address" },
    { jp: "～を維持する、整備する", en: "Maintain" },
    { jp: "悪意のある", en: "Malicious" },
    { jp: "マルウェア", en: "Malware" },
    { jp: "中間者攻撃", en: "Man in the middle" },
    { jp: "～を管理する", en: "Manage" },
    { jp: "手動の マニュアル", en: "Manual" },
    { jp: "大規模な", en: "Massive" },
    { jp: "対策、基準、(複数形で)方法、～を測定する", en: "Measure" },
    { jp: "医療の", en: "Medical" },
    { jp: "メモリ", en: "Memory" },
    { jp: "方法、方式", en: "Method" },
    { jp: "多要素認証", en: "Mfa" },
    { jp: "マイクロサービス", en: "Microservices" },
    { jp: "～を軽減する、緩和する", en: "Mitigate" },
    { jp: "～を変更する", en: "Modify" },
    { jp: "～を監視する 画面、監視", en: "Monitor" },
    { jp: "監視", en: "Monitoring" },
    { jp: "多数の", en: "Multiple" },
    { jp: "ほとんど", en: "Nearly" },
    { jp: "～に注意を払う、〜と述べる", en: "Note" },
    { jp: "～に通知する", en: "Notify" },
    { jp: "多数の", en: "Numerous" },
    { jp: "難読化", en: "Obfuscation" },
    { jp: "～を観測する、観察する", en: "Observe" },
    { jp: "～を得る", en: "Obtain" },
    { jp: "起こる", en: "Occur" },
    { jp: "〜を提供する 申し出、提供", en: "Offer" },
    { jp: "ワンタイム", en: "One time" },
    { jp: "進行中の", en: "Ongoing" },
    { jp: "～を運用する、操作する", en: "Operate" },
    { jp: "OS", en: "Operating system" },
    { jp: "機会", en: "Opportunity" },
    { jp: "選択肢、オプション", en: "Option" },
    { jp: "組織", en: "Organization" },
    { jp: "(システムなどの)停止", en: "Outage" },
    { jp: "パケット", en: "Packet" },
    { jp: "特に、特定の", en: "Particular" },
    { jp: "パスワード", en: "Password" },
    { jp: "パッチ", en: "Patch" },
    { jp: "進路、(ファイルの)パス", en: "Path" },
    { jp: "患者 忍耐強い", en: "Patient" },
    { jp: "〜を支払う、(注意など)を払う", en: "Pay" },
    { jp: "ペネトレーションテスト", en: "Pentest" },
    { jp: "許可", en: "Permission" },
    { jp: "個人の", en: "Personal" },
    { jp: "個人情報", en: "Personaldata" },
    { jp: "フィッシングを行う", en: "Phish" },
    { jp: "フィッシング", en: "Phishing" },
    { jp: "パイプライン", en: "Pipeline" },
    { jp: "ポリシー", en: "Policy" },
    { jp: "ポート", en: "Port" },
    { jp: "～を引き起こす、〜のふりをする", en: "Pose" },
    { jp: "～を投稿する 投稿", en: "Post" },
    { jp: "潜在的な 潜在的な", en: "Potential" },
    { jp: "報道 ～を押す", en: "Press" },
    { jp: "〜を妨げる", en: "Prevent" },
    { jp: "先の、以前の", en: "Previous" },
    { jp: "価格 ～に値段をつける", en: "Price" },
    { jp: "優先度、優先すべきこと", en: "Priority" },
    { jp: "刑務所", en: "Prison" },
    { jp: "プライバシー", en: "Privacy" },
    { jp: "内密の、私用の", en: "Private" },
    { jp: "秘密鍵", en: "Private key" },
    { jp: "特権", en: "Privilege" },
    { jp: "権限昇格", en: "Privilege escalation" },
    { jp: "手順、手続き", en: "Procedure" },
    { jp: "過程、工程 〜を処理する、手続きを行う", en: "Process" },
    { jp: "注目度、プロフィール 概略を描く", en: "Profile" },
    { jp: "〜を促進する", en: "Promote" },
    { jp: "～するように促す 迅速な、即座の", en: "Prompt" },
    { jp: "プロトコル", en: "Protocol" },
    { jp: "～を提供する", en: "Provide" },
    { jp: "プロキシ", en: "Proxy" },
    { jp: "公共の、公然の 大衆", en: "Public" },
    { jp: "公開鍵", en: "Public key" },
    { jp: "〜を発行する、出版する", en: "Publish" },
    { jp: "〜を購入する 購入", en: "Purchase" },
    { jp: "～を押し出す、配信する", en: "Push" },
    { jp: "検疫", en: "Quarantine" },
    { jp: "四半期", en: "Quarter" },
    { jp: "乱数", en: "Randomnumber" },
    { jp: "～から～に及ぶ 範囲", en: "Range" },
    { jp: "身代金", en: "Ransom" },
    { jp: "ランサムウェア", en: "Ransomware" },
    { jp: "～と評価する、見積もる 割合", en: "Rate" },
    { jp: "～よりむしろ", en: "Rather" },
    { jp: "最近の", en: "Recent" },
    { jp: "〜を推奨する", en: "Recommend" },
    { jp: "～を回復する", en: "Recover" },
    { jp: "リカバリ", en: "Recovery" },
    { jp: "～に登録する", en: "Register" },
    { jp: "～に関連する", en: "Relate" },
    { jp: "～を入手可能な状態にする (記事やプログラムの)リリース", en: "Release" },
    { jp: "～に依存する、～を信頼する", en: "Rely" },
    { jp: "遠隔の、遠隔からの", en: "Remote" },
    { jp: "〜を〜に取り替える", en: "Replace" },
    { jp: "伝えられるところによれば", en: "Reportedly" },
    { jp: "リポジトリ", en: "Repository" },
    { jp: "否認", en: "Repudiation" },
    { jp: "～を要求する、要請する 要請、リクエスト", en: "Request" },
    { jp: "〜を必要とする、要求する", en: "Require" },
    { jp: "～を解決する、名前解決する", en: "Resolve" },
    { jp: "対応する、応答する", en: "Respond" },
    { jp: "～の原因である、責任がある", en: "Responsible" },
    { jp: "～を復旧する、元に戻す", en: "Restore" },
    { jp: "〜を明らかにする", en: "Reveal" },
    { jp: "～を見直す、よく調べる 概観、見直し", en: "Review" },
    { jp: "リスク", en: "Risk" },
    { jp: "役割", en: "Role" },
    { jp: "ルートキット", en: "Rootkit" },
    { jp: "だいたい", en: "Roughly" },
    { jp: "ルーター", en: "Router" },
    { jp: "RSA", en: "Rsa" },
    { jp: "制裁 ～に制裁措置を取る", en: "Sanction" },
    { jp: "サンドボックス", en: "Sandbox" },
    { jp: "サニタイズ", en: "Sanitization" },
    { jp: "詐欺", en: "Scam" },
    { jp: "仕組み、悪だくみ、スキーム", en: "Scheme" },
    { jp: "スクリプトキディ", en: "Scriptkiddie" },
    { jp: "～を探す、検索する 探索、検索", en: "Search" },
    { jp: "業界、分野", en: "Sector" },
    { jp: "～を安全にする 安全な、セキュアな", en: "Secure" },
    { jp: "セキュリティ", en: "Security" },
    { jp: "～を求める、探す", en: "Seek" },
    { jp: "〜と思われる", en: "Seem" },
    { jp: "〜を押収する、〜を掴む", en: "Seize" },
    { jp: "上級の", en: "Senior" },
    { jp: "機微な、取扱注意の", en: "Sensitive" },
    { jp: "サーバー", en: "Server" },
    { jp: "サーバーレス", en: "Serverless" },
    { jp: "セッション", en: "Session" },
    { jp: "設定、環境", en: "Setting" },
    { jp: "いくつかの", en: "Several" },
    { jp: "深刻な", en: "Severe" },
    { jp: "シャドーIT", en: "Shadowit" },
    { jp: "電子署名", en: "Signature" },
    { jp: "シグネチャ", en: "Signature" },
    { jp: "著しい、重要な", en: "Significant" },
    { jp: "SOC", en: "Soc" },
    { jp: "社会の、社会的な", en: "Social" },
    { jp: "ソーシャルエンジニアリング", en: "Social engineering" },
    { jp: "洗練された", en: "Sophisticated" },
    { jp: "出所", en: "Source" },
    { jp: "スパム", en: "Spam" },
    { jp: "特定の、明白な", en: "Specific" },
    { jp: "なりすまし", en: "Spoofing" },
    { jp: "スパイウェア", en: "Spyware" },
    { jp: "SQLインジェクション", en: "Sql injection" },
    { jp: "SSL/TLS", en: "Ssl tls" },
    { jp: "〜と表明する 状態、国", en: "State" },
    { jp: "状態", en: "Status" },
    { jp: "～を盗む", en: "Steal" },
    { jp: "ストレージ", en: "Storage" },
    { jp: "戦略", en: "Strategy" },
    { jp: "〜を提出する", en: "Submit" },
    { jp: "成功", en: "Success" },
    { jp: "～を提案する、示唆する", en: "Suggest" },
    { jp: "供給 ～を供給する", en: "Supply" },
    { jp: "(アンケートなどによる)調査 ～を調査する、査定する", en: "Survey" },
    { jp: "疑わしい、不審な", en: "Suspicious" },
    { jp: "スイッチ", en: "Switch" },
    { jp: "～を切り替える 転換、スイッチ", en: "Switch" },
    { jp: "戦術", en: "Tactic" },
    { jp: "改ざん", en: "Tampering" },
    { jp: "～を標的とする 標的", en: "Target" },
    { jp: "仕事、タスク (仕事)を割り当てる", en: "Task" },
    { jp: "税金", en: "Tax" },
    { jp: "手法、テクニック", en: "Technique" },
    { jp: "(利用などの)規約、期間、用語", en: "Term" },
    { jp: "窃盗", en: "Theft" },
    { jp: "したがって", en: "Therefore" },
    { jp: "脅威", en: "Threat" },
    { jp: "トークン", en: "Token" },
    { jp: "道具、ツール", en: "Tool" },
    { jp: "Tor", en: "Tor" },
    { jp: "〜を追跡する", en: "Track" },
    { jp: "〜をだます", en: "Trick" },
    { jp: "～のきっかけとなる 引き金、トリガー", en: "Trigger" },
    { jp: "トロイの木馬", en: "Trojan" },
    { jp: "～を信用する 信用", en: "Trust" },
    { jp: "型、タイプ", en: "Type" },
    { jp: "典型的な", en: "Typical" },
    { jp: "不運なことに", en: "Unfortunately" },
    { jp: "～に～するように強く要請する", en: "Urge" },
    { jp: "USB", en: "Usb" },
    { jp: "～を利用する", en: "Utilize" },
    { jp: "値、価値 ～を評価する、尊重する", en: "Value" },
    { jp: "(マルウェアなどの)亜種、変異種", en: "Variant" },
    { jp: "経路、方向", en: "Vector" },
    { jp: "～を検証する", en: "Verify" },
    { jp: "被害者", en: "Victim" },
    { jp: "仮想化", en: "Virtualization" },
    { jp: "ウイルス", en: "Virus" },
    { jp: "量、ボリューム", en: "Volume" },
    { jp: "VPN", en: "Vpn" },
    { jp: "脆弱性", en: "Vulnerability" },
    { jp: "～を警告する", en: "Warn" },
    { jp: "水飲み場攻撃", en: "Wateringhole" },
    { jp: "ホワイトハット", en: "Whitehat" },
    { jp: "ホワイトリスト", en: "Whitelist" },
    { jp: "Windows", en: "Windows" },
    { jp: "(データなど)を削除する", en: "Wipe" },
    { jp: "回避策、緩和策", en: "Workaround" },
    { jp: "ワーム", en: "Worm" },
    { jp: "クロスサイトスクリプト", en: "Xss" },
    { jp: "ゼロデイ", en: "Zero day" },
    { jp: "ゼロトラスト", en: "Zerotrust" },
];

