const termList = [
    { jp: "ファイアウォール", en: "FIREWALL" },
    { jp: "マルウェア", en: "MALWARE" },
    { jp: "ウイルス", en: "VIRUS" },
    { jp: "トロイの木馬", en: "TROJAN" },
    { jp: "ワーム", en: "WORM" },
    { jp: "スパイウェア", en: "SPYWARE" },
    { jp: "ランサムウェア", en: "RANSOMWARE" },
    { jp: "フィッシング", en: "PHISHING" },
    { jp: "脆弱性", en: "VULNERABILITY" },
    { jp: "エクスプロイト", en: "EXPLOIT" },
    { jp: "バグ", en: "BUG" },
    { jp: "パッチ", "en": "PATCH" },
    { jp: "ハッキング", "en": "HACKING" },
    { jp: "サイバー", "en": "CYBER" },
    { jp: "セキュリティ", "en": "SECURITY" },
    { jp: "アラート", "en": "ALERT" },
    { jp: "アクセス", "en": "ACCESS" },
    { jp: "ログイン", "en": "LOGIN" },
    { jp: "ログアウト", "en": "LOGOUT" },
    { jp: "管理者", "en": "ADMIN" },
    { jp: "プロトコル", "en": "PROTOCOL" },
    { jp: "パケット", "en": "PACKET" },
    { jp: "サーバー", "en": "SERVER" },
    { jp: "クライアント", "en": "CLIENT" },
    { jp: "クラウド", "en": "CLOUD" },
    { jp: "VPN", "en": "VPN" },
    { jp: "プロキシ", "en": "PROXY" },
    { jp: "ルーター", "en": "ROUTER" },
    { jp: "スイッチ", "en": "SWITCH" },
    { jp: "ゲートウェイ", "en": "GATEWAY" },
    { jp: "ポート", "en": "PORT" },
    { jp: "IPアドレス", "en": "IP ADDRESS" },
    { jp: "MACアドレス", "en": "MAC ADDRESS" },
    { jp: "ドメイン", "en": "DOMAIN" },
    { jp: "DNS", "en": "DNS" },
    { jp: "DHCP", "en": "DHCP" },
    { jp: "イントラネット", "en": "INTRANET" },
    { jp: "インターネット", "en": "INTERNET" },
    { jp: "DMZ", "en": "DMZ" },
    { jp: "帯域幅", "en": "BANDWIDTH" },
    { jp: "レイテンシ", "en": "LATENCY" },
    { jp: "認証", "en": "AUTHENTICATION" },
    { jp: "認可", "en": "AUTHORIZATION" },
    { jp: "暗号化", "en": "ENCRYPTION" },
    { jp: "復号", "en": "DECRYPTION" },
    { jp: "ハッシュ", "en": "HASH" },
    { jp: "ブロックチェーン", "en": "BLOCKCHAIN" },
    { jp: "多要素認証", "en": "MFA" },
    { jp: "生体認証", "en": "BIOMETRIC" },
    { jp: "公開鍵", "en": "PUBLIC KEY" },
    { jp: "秘密鍵", "en": "PRIVATE KEY" },
    { jp: "電子署名", "en": "SIGNATURE" },
    { jp: "証明書", "en": "CERTIFICATE" },
    { jp: "トークン", "en": "TOKEN" },
    { jp: "パスワード", "en": "PASSWORD" },
    { jp: "ワンタイム", "en": "ONE TIME" },
    { jp: "SSL/TLS", "en": "SSL TLS" },
    { jp: "RSA", "en": "RSA" },
    { jp: "バックドア", "en": "BACKDOOR" },
    { jp: "ボットネット", "en": "BOTNET" },
    { jp: "ゼロデイ", "en": "ZERO DAY" },
    { jp: "ソーシャルエンジニアリング", "en": "SOCIAL ENGINEERING" },
    { jp: "権限昇格", "en": "PRIVILEGE ESCALATION" },
    { jp: "盗聴", "en": "EAVESDROPPING" },
    { jp: "改ざん", "en": "TAMPERING" },
    { jp: "なりすまし", "en": "SPOOFING" },
    { jp: "否認", "en": "REPUDIATION" },
    { jp: "ブルートフォース", "en": "BRUTE FORCE" },
    { jp: "辞書攻撃", "en": "DICTIONARY ATTACK" },
    { jp: "SQLインジェクション", "en": "SQL INJECTION" },
    { jp: "クロスサイトスクリプト", "en": "XSS" },
    { jp: "中間者攻撃", "en": "MAN IN THE MIDDLE" },
    { jp: "サービス拒否", "en": "DOS" },
    { jp: "DDoS攻撃", "en": "DDOS" },
    { jp: "キーロガー", "en": "KEYLOGGER" },
    { jp: "ルートキット", "en": "ROOTKIT" },
    { jp: "スパム", "en": "SPAM" },
    { jp: "標的型攻撃", "en": "APT" },
    { jp: "踏み台", "en": "JUMPHOST" },
    { jp: "水飲み場攻撃", "en": "WATERINGHOLE" },
    { jp: "クリックジャッキング", "en": "CLICKJACKING" },
    { jp: "リスク", "en": "RISK" },
    { jp: "資産", "en": "ASSET" },
    { jp: "脅威", "en": "THREAT" },
    { jp: "監査", "en": "AUDIT" },
    { jp: "コンプライアンス", "en": "COMPLIANCE" },
    { jp: "ポリシー", "en": "POLICY" },
    { jp: "インテグリティ", "en": "INTEGRITY" },
    { jp: "可用性", "en": "AVAILABILITY" },
    { jp: "機密性", "en": "CONFIDENTIALITY" },
    { jp: "情報漏洩", "en": "LEAKAGE" },
    { jp: "バックアップ", "en": "BACKUP" },
    { jp: "リカバリ", "en": "RECOVERY" },
    { jp: "検知", "en": "DETECTION" },
    { jp: "防御", "en": "DEFENSE" },
    { jp: "監視", "en": "MONITORING" },
    { jp: "ログ", "en": "LOG" },
    { jp: "分析", "en": "ANALYSIS" },
    { jp: "フォレンジック", "en": "FORENSICS" },
    { jp: "ペネトレーションテスト", "en": "PENTEST" },
    { jp: "バグバウンティ", "en": "BUGBOUNTY" },
    { jp: "インシデント", "en": "INCIDENT" },
    { jp: "CSIRT", "en": "CSIRT" },
    { jp: "SOC", "en": "SOC" },
    { jp: "ゼロトラスト", "en": "ZEROTRUST" },
    { jp: "バイオス", "en": "BIOS" },
    { jp: "カーネル", "en": "KERNEL" },
    { jp: "メモリ", "en": "MEMORY" },
    { jp: "CPU", "en": "CPU" },
    { jp: "GPU", "en": "GPU" },
    { jp: "ストレージ", "en": "STORAGE" },
    { jp: "USB", "en": "USB" },
    { jp: "ファームウェア", "en": "FIRMWARE" },
    { jp: "ドライバ", "en": "DRIVER" },
    { jp: "仮想化", "en": "VIRTUALIZATION" },
    { jp: "コンテナ", "en": "CONTAINER" },
    { jp: "IoT", "en": "INTERNET OF THINGS" },
    { jp: "OS", "en": "OPERATING SYSTEM" },
    { jp: "Windows", "en": "WINDOWS" },
    { jp: "Linux", "en": "LINUX" },
    { jp: "Mac", "en": "MAC" },
    { jp: "Android", "en": "ANDROID" },
    { jp: "iOS", "en": "IOS" },
    { jp: "データベース", "en": "DATABASE" },
    { jp: "アルゴリズム", "en": "ALGORITHM" },
    { jp: "ホワイトハット", "en": "WHITEHAT" },
    { jp: "ブラックハット", "en": "BLACKHAT" },
    { jp: "グレーハット", "en": "GRAYHAT" },
    { jp: "スクリプトキディ", "en": "SCRIPTKIDDIE" },
    { jp: "ハクティビスト", "en": "HACKTIVIST" },
    { jp: "ダークウェブ", "en": "DARKWEB" },
    { jp: "ディープウェブ", "en": "DEEPWEB" },
    { jp: "Tor", "en": "TOR" },
    { jp: "ビットコイン", "en": "BITCOIN" },
    { jp: "エビデンス", "en": "EVIDENCE" },
    { jp: "隔離", "en": "ISOLATION" },
    { jp: "サニタイズ", "en": "SANITIZATION" },
    { jp: "フィルタリング", "en": "FILTERING" },
    { jp: "ホワイトリスト", "en": "WHITELIST" },
    { jp: "ブラックリスト", "en": "BLACKLIST" },
    { jp: "サンドボックス", "en": "SANDBOX" },
    { jp: "ハニーポット", "en": "HONEYPOT" },
    { jp: "個人情報", "en": "PERSONALDATA" },
    { jp: "プライバシー", "en": "PRIVACY" },
    { jp: "著作権", "en": "COPYRIGHT" },
    { jp: "パイプライン", "en": "PIPELINE" },
    { jp: "デプロイ", "en": "DEPLOY" },
    { jp: "リポジトリ", "en": "REPOSITORY" },
    { jp: "マイクロサービス", "en": "MICROSERVICES" },
    { jp: "サーバーレス", "en": "SERVERLESS" },
    { jp: "シャドーIT", "en": "SHADOWIT" },
    { jp: "共通鍵", "en": "COMMONKEY" },
    { jp: "鍵交換", "en": "KEYEXCHANGE" },
    { jp: "乱数", "en": "RANDOMNUMBER" },
    { jp: "堅牢化", "en": "HARDENING" },
    { jp: "難読化", "en": "OBFUSCATION" },
    { jp: "検疫", "en": "QUARANTINE" },
    { jp: "シグネチャ", "en": "SIGNATURE" },
    { jp: "エアギャップ", "en": "AIRGAP" },
    { jp: "最小権限", "en": "LEASTPRIVILEGE" },
    { jp: "多層防御", "en": "DEFENSEINDEPTH" },
    { jp: "クッキー", "en": "COOKIE" },
    { jp: "セッション", "en": "SESSION" },
    { jp: "～を含む", en: "INCLUDE" },
    { jp: "～を盗む", en: "STEAL" },
    { jp: "～を入手可能な状態にする (記事やプログラムの)リリース", en: "RELEASE" },
    { jp: "～を標的とする 標的", en: "TARGET" },
    { jp: "～を可能とする、許可する", en: "ALLOW" },
    { jp: "～を提供する", en: "PROVIDE" },
    { jp: "～を作り出す", en: "CREATE" },
    { jp: "(システムなど)を侵害する", en: "COMPROMISE" },
    { jp: "～を警告する", en: "WARN" },
    { jp: "(設定などを) 有効化する、可能にする", en: "ENABLE" },
    { jp: "〜を暴露する", en: "EXPOSE" },
    { jp: "〜に影響する", en: "AFFECT" },
    { jp: "(脆弱性やバグ)を修正する", en: "FIX" },
    { jp: "〜と主張する 主張、要求", en: "CLAIM" },
    { jp: "〜を含む", en: "CONTAIN" },
    { jp: "〜を支払う、(注意など)を払う", en: "PAY" },
    { jp: "〜と表明する 状態、国", en: "STATE" },
    { jp: "〜を確認する", en: "CONFIRM" },
    { jp: "〜を妨げる", en: "PREVENT" },
    { jp: "〜を発行する、出版する", en: "PUBLISH" },
    { jp: "〜を検知する", en: "DETECT" },
    { jp: "〜を必要とする、要求する", en: "REQUIRE" },
    { jp: "～を立ち上げる、～を開始する 開始", en: "LAUNCH" },
    { jp: "〜を遮断する ブロック、遮断", en: "BLOCK" },
    { jp: "〜を提供する 申し出、提供", en: "OFFER" },
    { jp: "〜を明らかにする", en: "REVEAL" },
    { jp: "〜を特定する", en: "IDENTIFY" },
    { jp: "流出する、〜を流出させる (情報の)流出、リーク", en: "LEAK" },
    { jp: "～を暗号化する", en: "ENCRYPT" },
    { jp: "～を復号する", en: "DECRYPT" },
    { jp: "～を獲得する 収益", en: "GAIN" },
    { jp: "〜を公表する、暴露する", en: "DISCLOSE" },
    { jp: "〜を基盤とする、～に基づく 基盤、基礎、基数", en: "BASE" },
    { jp: "～を実行する", en: "EXECUTE" },
    { jp: "～を管理する", en: "MANAGE" },
    { jp: "(問題やバグなど)に対処する 住所、アドレス", en: "ADDRESS" },
    { jp: "〜を確実にする、保証する", en: "ENSURE" },
    { jp: "フィッシングを行う", en: "PHISH" },
    { jp: "～に注意を払う、〜と述べる", en: "NOTE" },
    { jp: "〜を追跡する", en: "TRACK" },
    { jp: "～を配送する", en: "DELIVER" },
    { jp: "～を試みる 試み", en: "ATTEMPT" },
    { jp: "～を運用する、操作する", en: "OPERATE" },
    { jp: "〜を巻き込む、関係させる", en: "INVOLVE" },
    { jp: "～に関連する", en: "RELATE" },
    { jp: "～を調査する", en: "INVESTIGATE" },
    { jp: "～を安全にする 安全な、セキュアな", en: "SECURE" },
    { jp: "〜を推奨する", en: "RECOMMEND" },
    { jp: "〜と接触する、連絡する 接触", en: "CONTACT" },
    { jp: "〜を無効化する", en: "DISABLE" },
    { jp: "〜を削除する", en: "DELETE" },
    { jp: "存在する、すでにある", en: "EXIST" },
    { jp: "〜を予期する、〜と推定する", en: "EXPECT" },
    { jp: "～と関連づける 関連、リンク", en: "LINK" },
    { jp: "失敗する", en: "FAIL" },
    { jp: "～を行う 行為", en: "CONDUCT" },
    { jp: "～を配布する", en: "DISTRIBUTE" },
    { jp: "～を観測する、観察する", en: "OBSERVE" },
    { jp: "～に～するように強く要請する", en: "URGE" },
    { jp: "～になりすます", en: "IMPERSONATE" },
    { jp: "～を忠告する、勧める", en: "ADVISE" },
    { jp: "起こる", en: "OCCUR" },
    { jp: "～を表示する、展示する 表示、画面", en: "DISPLAY" },
    { jp: "～に集中する、焦点を当てる 焦点、中心", en: "FOCUS" },
    { jp: "～を決心する、判断する", en: "DETERMINE" },
    { jp: "～を投稿する 投稿", en: "POST" },
    { jp: "～をよく考える、検討する、考慮する", en: "CONSIDER" },
    { jp: "～を解決する、名前解決する", en: "RESOLVE" },
    { jp: "～を強いる 強制、暴力", en: "FORCE" },
    { jp: "～を得る", en: "OBTAIN" },
    { jp: "～を監視する 画面、監視", en: "MONITOR" },
    { jp: "～を分析する", en: "ANALYZE" },
    { jp: "～と関連付ける 仲間", en: "ASSOCIATE" },
    { jp: "～を悪用する 悪用、不正行為", en: "ABUSE" },
    { jp: "～を実装する、実行する", en: "IMPLEMENT" },
    { jp: "～に感染させる", en: "INFECT" },
    { jp: "～を軽減する、緩和する", en: "MITIGATE" },
    { jp: "～を迂回する 迂回、バイパス", en: "BYPASS" },
    { jp: "～を強調する 目玉、見どころ", en: "HIGHLIGHT" },
    { jp: "～を付け加える", en: "APPEND" },
    { jp: "～に通知する", en: "NOTIFY" },
    { jp: "～を設定する", en: "CONFIGURE" },
    { jp: "～を復旧する、元に戻す", en: "RESTORE" },
    { jp: "～と主張する", en: "ARGUE" },
    { jp: "～と説明する、記述する", en: "DESCRIBE" },
    { jp: "～を生成する、生じさせる", en: "GENERATE" },
    { jp: "～を避ける", en: "AVOID" },
    { jp: "～に属する", en: "BELONG" },
    { jp: "～を示す、指摘する", en: "INDICATE" },
    { jp: "対応する、応答する", en: "RESPOND" },
    { jp: "～を隠す", en: "HIDE" },
    { jp: "～を回復する", en: "RECOVER" },
    { jp: "～を提案する、示唆する", en: "SUGGEST" },
    { jp: "～に知らせる", en: "INFORM" },
    { jp: "(罪など)を犯す、～を約束する", en: "COMMIT" },
    { jp: "～に依存する、～を信頼する", en: "RELY" },
    { jp: "～を検証する", en: "VERIFY" },
    { jp: "～を中断させる、混乱させる", en: "DISRUPT" },
    { jp: "～を押し出す、配信する", en: "PUSH" },
    { jp: "～を告発する、請求する 請求、告発", en: "CHARGE" },
    { jp: "～を限定する、制限する 限界、制限", en: "LIMIT" },
    { jp: "～を切り替える 転換、スイッチ", en: "SWITCH" },
    { jp: "～に登録する", en: "REGISTER" },
    { jp: "～を維持する、整備する", en: "MAINTAIN" },
    { jp: "～を利用する", en: "UTILIZE" },
    { jp: "～を確立する", en: "ESTABLISH" },
    { jp: "(データなど)を削除する", en: "WIPE" },
    { jp: "～を変更する", en: "MODIFY" },
    { jp: "～のきっかけとなる 引き金、トリガー", en: "TRIGGER" },
    { jp: "(データなど)を密かに流出させる", en: "EXFILTRATE" },
    { jp: "～するように促す 迅速な、即座の", en: "PROMPT" },
    { jp: "～を組み込む、埋め込む", en: "EMBED" },
    { jp: "～を求める、探す", en: "SEEK" },
    { jp: "広がる、〜を広げる", en: "EXPAND" },
    { jp: "〜に携わる、〜を雇う", en: "ENGAGE" },
    { jp: "〜を〜に取り替える", en: "REPLACE" },
    { jp: "〜と思われる", en: "SEEM" },
    { jp: "～を要求する 要求", en: "DEMAND" },
    { jp: "〜を防御する", en: "DEFEND" },
    { jp: "〜をだます", en: "TRICK" },
    { jp: "～を引き起こす、〜のふりをする", en: "POSE" },
    { jp: "〜を促進する", en: "PROMOTE" },
    { jp: "台頭する、現れる、明らかになる", en: "EMERGE" },
    { jp: "～を信用する 信用", en: "TRUST" },
    { jp: "〜を達成する、獲得する", en: "ACHIEVE" },
    { jp: "〜を調整する、まとめ上げる", en: "COORDINATE" },
    { jp: "〜を狙う、目指す 狙い、目的", en: "AIM" },
    { jp: "〜を提出する", en: "SUBMIT" },
    { jp: "〜を認める、入れる", en: "ADMIT" },
    { jp: "～に関係する 関係、関心事", en: "CONCERN" },
    { jp: "〜を注入する、仕掛ける", en: "INJECT" },
    { jp: "〜と主張する", en: "ALLEGE" },
    { jp: "～を自動化する", en: "AUTOMATE" },
    { jp: "〜を購入する 購入", en: "PURCHASE" },
    { jp: "〜と結論づける", en: "CONCLUDE" },
    { jp: "〜を示す、証明する", en: "DEMONSTRATE" },
    { jp: "〜に置く", en: "LOCATE" },
    { jp: "～を要求する、要請する 要請、リクエスト", en: "REQUEST" },
    { jp: "〜を押収する、〜を掴む", en: "SEIZE" },
    { jp: "～を扱う、処理する", en: "HANDLE" },
    { jp: "～を完了する 全部の、完全な", en: "COMPLETE" },
    { jp: "～を見直す、よく調べる 概観、見直し", en: "REVIEW" },
    { jp: "～を雇う、使用する", en: "EMPLOY" },
    { jp: "～を認証する", en: "AUTHENTICATE" },
    { jp: "～を探す、検索する 探索、検索", en: "SEARCH" },
    { jp: "～を投資する", en: "INVEST" },
    { jp: "〜を破壊する、クラッシュする (装置・プログラムの)クラッシュ", en: "CRASH" },
    { jp: "～から～に及ぶ 範囲", en: "RANGE" },
    { jp: "～を拡張する、広げる", en: "EXTEND" },
    { jp: "～を脅迫する、ゆすり取る", en: "EXTORT" },
    { jp: "～を強要する、実施する", en: "ENFORCE" },
    { jp: "～と評価する、見積もる 割合", en: "RATE" },
    { jp: "進歩する 進歩、前進", en: "ADVANCE" },
    { jp: "～を指示する、～へ案内する 直接の", en: "DIRECT" },
    { jp: "～を添付する、取り付ける", en: "ATTACH" },
    { jp: "～を認可する、権限を与える", en: "AUTHORIZE" },
    { jp: "攻撃者グループ、アクター", en: "ACTOR" },
    { jp: "問題(点) 〜を発行する", en: "ISSUE" },
    { jp: "顧客、取引先", en: "CUSTOMER" },
    { jp: "被害者", en: "VICTIM" },
    { jp: "アカウント、口座", en: "ACCOUNT" },
    { jp: "組織", en: "ORGANIZATION" },
    { jp: "コード、符号", en: "CODE" },
    { jp: "(データの)流出、侵害 ～を侵害しデータを持ち出す", en: "BREACH" },
    { jp: "特徴、目玉 ～を売りとする、特集する", en: "FEATURE" },
    { jp: "一連の作戦、キャンペーン", en: "CAMPAIGN" },
    { jp: "政府", en: "GOVERNMENT" },
    { jp: "道具、ツール", en: "TOOL" },
    { jp: "欠陥", en: "FLAW" },
    { jp: "出所", en: "SOURCE" },
    { jp: "身代金", en: "RANSOM" },
    { jp: "会社", en: "FIRM" },
    { jp: "過程、工程 〜を処理する、手続きを行う", en: "PROCESS" },
    { jp: "細部、詳細 〜を詳細に述べる", en: "DETAIL" },
    { jp: "法", en: "LAW" },
    { jp: "機関", en: "AGENCY" },
    { jp: "詐欺", en: "SCAM" },
    { jp: "詐欺", en: "FRAUD" },
    { jp: "詐欺師", en: "FRAUDSTER" },
    { jp: "設定、環境", en: "SETTING" },
    { jp: "画像、イメージ", en: "IMAGE" },
    { jp: "(マルウェアなどの)亜種、変異種", en: "VARIANT" },
    { jp: "産業、業界", en: "INDUSTRY" },
    { jp: "個人 個人の、個々の", en: "INDIVIDUAL" },
    { jp: "特権", en: "PRIVILEGE" },
    { jp: "型、タイプ", en: "TYPE" },
    { jp: "業界、分野", en: "SECTOR" },
    { jp: "省、局", en: "DEPARTMENT" },
    { jp: "識別情報", en: "IDENTITY" },
    { jp: "暗号通貨", en: "CRYPTOCURRENCY" },
    { jp: "内容、コンテンツ", en: "CONTENT" },
    { jp: "企業", en: "ENTERPRISE" },
    { jp: "接続、コネクション", en: "CONNECTION" },
    { jp: "形態、種類、フォーム", en: "FORM" },
    { jp: "方法、方式", en: "METHOD" },
    { jp: "選択肢、オプション", en: "OPTION" },
    { jp: "知能、インテリジェンス", en: "INTELLIGENCE" },
    { jp: "(システムなどの)停止", en: "OUTAGE" },
    { jp: "窃盗", en: "THEFT" },
    { jp: "消費者", en: "CONSUMER" },
    { jp: "能力", en: "CAPABILITY" },
    { jp: "戦術", en: "TACTIC" },
    { jp: "対策、基準、(複数形で)方法、～を測定する", en: "MEASURE" },
    { jp: "手法、テクニック", en: "TECHNIQUE" },
    { jp: "付加", en: "ADDITION" },
    { jp: "管理者", en: "ADMINISTRATOR" },
    { jp: "経路、チャンネル", en: "CHANNEL" },
    { jp: "量、総計 (to～で)～に達する", en: "AMOUNT" },
    { jp: "加盟メンバー ～に加盟する", en: "AFFILIATE" },
    { jp: "損害、喪失", en: "LOSS" },
    { jp: "(人や組織などの)主体", en: "ENTITY" },
    { jp: "値、価値 ～を評価する、尊重する", en: "VALUE" },
    { jp: "役割", en: "ROLE" },
    { jp: "当局、権威", en: "AUTHORITY" },
    { jp: "取り組み方、接近 取り組み方、接近", en: "APPROACH" },
    { jp: "供給 ～を供給する", en: "SUPPLY" },
    { jp: "挙動、振る舞い", en: "BEHAVIOR" },
    { jp: "仕組み、悪だくみ、スキーム", en: "SCHEME" },
    { jp: "例、インスタンス", en: "INSTANCE" },
    { jp: "能力", en: "ABILITY" },
    { jp: "資金、基金 ～に資金提供する", en: "FUND" },
    { jp: "患者 忍耐強い", en: "PATIENT" },
    { jp: "犯罪", en: "CRIME" },
    { jp: "注目度、プロフィール 概略を描く", en: "PROFILE" },
    { jp: "機会", en: "OPPORTUNITY" },
    { jp: "機能、関数 機能する", en: "FUNCTION" },
    { jp: "興味、関心事 興味を起こさせる", en: "INTEREST" },
    { jp: "(利用などの)規約、期間、用語", en: "TERM" },
    { jp: "量、ボリューム", en: "VOLUME" },
    { jp: "税金", en: "TAX" },
    { jp: "許可", en: "PERMISSION" },
    { jp: "内部の人、会員", en: "INSIDER" },
    { jp: "仕事、タスク (仕事)を割り当てる", en: "TASK" },
    { jp: "機関、団体", en: "INSTITUTION" },
    { jp: "戦略", en: "STRATEGY" },
    { jp: "経路、方向", en: "VECTOR" },
    { jp: "記事", en: "ARTICLE" },
    { jp: "費用 (費用)がかかる", en: "COST" },
    { jp: "裁判所", en: "COURT" },
    { jp: "保険", en: "INSURANCE" },
    { jp: "報道 ～を押す", en: "PRESS" },
    { jp: "(take advantage of～で)～を利用する", en: "ADVANTAGE" },
    { jp: "進路、(ファイルの)パス", en: "PATH" },
    { jp: "(相手を騙すための) おとり、ルアー ～を誘い込む", en: "LURE" },
    { jp: "回避策、緩和策", en: "WORKAROUND" },
    { jp: "緊急事態", en: "EMERGENCY" },
    { jp: "(アンケートなどによる)調査 ～を調査する、査定する", en: "SURVEY" },
    { jp: "制裁 ～に制裁措置を取る", en: "SANCTION" },
    { jp: "報奨金", en: "BOUNTY" },
    { jp: "認証情報", en: "CREDENTIAL" },
    { jp: "選挙", en: "ELECTION" },
    { jp: "状態", en: "STATUS" },
    { jp: "苦情、告訴", en: "COMPLAINT" },
    { jp: "手順、手続き", en: "PROCEDURE" },
    { jp: "四半期", en: "QUARTER" },
    { jp: "行政長官、経営者", en: "EXECUTIVE" },
    { jp: "説明、指示、命令", en: "INSTRUCTION" },
    { jp: "価格 ～に値段をつける", en: "PRICE" },
    { jp: "優先度、優先すべきこと", en: "PRIORITY" },
    { jp: "入り口、項目", en: "ENTRY" },
    { jp: "刑務所", en: "PRISON" },
    { jp: "効果、影響", en: "EFFECT" },
    { jp: "成功", en: "SUCCESS" },
    { jp: "(権限の)昇格", en: "ELEVATION" },
    { jp: "悪意のある", en: "MALICIOUS" },
    { jp: "重大な、致命的な", en: "CRITICAL" },
    { jp: "遠隔の、遠隔からの", en: "REMOTE" },
    { jp: "利用可能である", en: "AVAILABLE" },
    { jp: "個人の", en: "PERSONAL" },
    { jp: "多数の", en: "MULTIPLE" },
    { jp: "公共の、公然の 大衆", en: "PUBLIC" },
    { jp: "金銭的な、金融の", en: "FINANCIAL" },
    { jp: "偽の", en: "FAKE" },
    { jp: "(dueto〜の形で)〜を原因として", en: "DUE" },
    { jp: "社会の、社会的な", en: "SOCIAL" },
    { jp: "機微な、取扱注意の", en: "SENSITIVE" },
    { jp: "ありそうな おそらく", en: "LIKELY" },
    { jp: "最近の", en: "RECENT" },
    { jp: "内密の、私用の", en: "PRIVATE" },
    { jp: "さらに進んだ さらに", en: "FURTHER" },
    { jp: "いくつかの", en: "SEVERAL" },
    { jp: "潜在的な 潜在的な", en: "POTENTIAL" },
    { jp: "正規の", en: "LEGITIMATE" },
    { jp: "進行中の", en: "ONGOING" },
    { jp: "現在の、最新の", en: "CURRENT" },
    { jp: "連邦の", en: "FEDERAL" },
    { jp: "内部の", en: "INTERNAL" },
    { jp: "外部の", en: "EXTERNAL" },
    { jp: "著しい、重要な", en: "SIGNIFICANT" },
    { jp: "法人の、企業の", en: "CORPORATE" },
    { jp: "先の、以前の", en: "PREVIOUS" },
    { jp: "ある特定の、確かな", en: "CERTAIN" },
    { jp: "特定の、明白な", en: "SPECIFIC" },
    { jp: "～を知っている", en: "AWARE" },
    { jp: "最初の", en: "INITIAL" },
    { jp: "医療の", en: "MEDICAL" },
    { jp: "疑わしい、不審な", en: "SUSPICIOUS" },
    { jp: "累積の", en: "CUMULATIVE" },
    { jp: "前の、先の", en: "FORMER" },
    { jp: "任意の", en: "ARBITRARY" },
    { jp: "大規模な", en: "MASSIVE" },
    { jp: "特に、特定の", en: "PARTICULAR" },
    { jp: "多数の", en: "NUMEROUS" },
    { jp: "～の原因である、責任がある", en: "RESPONSIBLE" },
    { jp: "上級の", en: "SENIOR" },
    { jp: "洗練された", en: "SOPHISTICATED" },
    { jp: "法的な、法曹業界の、合法の", en: "LEGAL" },
    { jp: "既知の", en: "KNOWN" },
    { jp: "全体の、完全な", en: "ENTIRE" },
    { jp: "偽の、間違った", en: "FALSE" },
    { jp: "深刻な", en: "SEVERE" },
    { jp: "機密の", en: "CONFIDENTIAL" },
    { jp: "即時の、即座の", en: "IMMEDIATE" },
    { jp: "典型的な", en: "TYPICAL" },
    { jp: "手動の マニュアル", en: "MANUAL" },
    { jp: "～によれば", en: "ACCORDING" },
    { jp: "ほとんど", en: "NEARLY" },
    { jp: "ますます", en: "INCREASINGLY" },
    { jp: "おおよそ", en: "APPROXIMATELY" },
    { jp: "～よりむしろ", en: "RATHER" },
    { jp: "不運なことに", en: "UNFORTUNATELY" },
    { jp: "したがって", en: "THEREFORE" },
    { jp: "だいたい", en: "ROUGHLY" },
    { jp: "伝えられるところによれば", en: "REPORTEDLY" },
];

